name: Bump Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update Lockfile
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "CI: bump flake inputs"

      - name: Merge Changes
        run: |
          gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
